const rankOptions = [
  'BRONZE 1',
  'BRONZE 2',
  'BRONZE 3',
  'SILVER 1',
  'SILVER 2',
  'SILVER 3',
  'GOLD 1',
  'GOLD 2',
  'GOLD 3',
  'PLATINUM 1',
  'PLATINUM 2',
  'PLATINUM 3',
  'DIAMOND 1',
  'DIAMOND 2',
  'DIAMOND 3',
  'CHAMPION 1',
  'CHAMPION 2',
  'CHAMPION 3',
  'GRAND CHAMPION 1',
  'GRAND CHAMPION 2',
  'GRAND CHAMPION 3',
  'SSL',
]

export default rankOptions;